version: '3'
services:
  chat-room-api:
    image: 'node:20-alpine3.16'
    hostname: 'chat-room-api'
    container_name: 'chat-room-api'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    command: 'npm run start:dev'

  postgres:
    image: 'postgres:13-alpine'
    hostname: 'postgres'
    container_name: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_room
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: chat-room-network
